import Article_Sweep
from collections import Counter

def main():
    manual_params = ['R0',
              'transmission_rate',
              'testing_rate',
              'mortality_rate',
              'case_fatality_ratio',
              'asymptomatic_rate',
              'undocumented_cases',
              'sample_size']

    auto_params = ['DOI',
                   'date',
                   'published_in',
                   'published_by',
                   'study_location_scope',
                   'methodology']

    keywords = ['transmission',
                'rate',
                'spread',
                'infection',
                'exposed',
                'mortality']

    bad_keywords = ['gene',
                    'ACE2',
                    'chloroquine',
                    'remdesivir',
                    'favipiravir',
                    'rhinitis',
                    'cytokine',
                    'expression',
                    'PROMOTOR',
                    'capacity',
                    # 'detection',
                    'ecological',
                    'cell',
                    'vaccine',
                    'Antibody',
                    'Structural',
                    'assay',
                    'Genome',
                    'administered',
                    'risk factor',
                    'cross-sectional',
                    # 'diagnosis',
                    'Chest',
                    'Retroviruses',
                    'replication',
                    'dna',
                    'rna',
                    'genetic',
                    'Evolutionary',
                    'psychological',
                    'vulnerability',
                    'genomics',
                    'features',
                    'clinical',
                    'protein',
                    'retrospective',
                    'Pre-existing',
                    'pre existing',
                    'Facebook',
                    'survey',
                    'goggle',
                    'receptor',
                    'proteases',
                    'surveillance',
                    'nucleo',
                    'influenza',
                    'blood',
                    'Antibodies',
                    'antibody',
                    'homology',
                    'Telemedicine',
                    'glyco',
                    'polymerase',
                    'enzyme',
                    'Kidney',
                    'serum',
                    'tool',
                    'strategy',
                    'bat',
                    'Ethics',
                    'inhibition',
                    'surgical',
                    'Working',
                    'flu',
                    'Students',
                    'reflect',
                    'VIRTUAL',
                    'Colleagues',
                    'hydroxychloroquine',
                    'Psychotic',
                    'education',
                    'Tourism',
                    'Effects',
                    'Stress',
                    'Dialysis',
                    'transplantation',
                    'mental',
                    'biologic',
                    'pain',
                    'ophthalmologist',
                    'chronic',
                    'Ventilator',
                    'stroke',
                    'Nucleic',
                    'Molecular',
                    'molecule',
                    'telehealth',
                    'resistance',
                    'NEWS',
                    'drugs',
                    'mobility',
                    'therapeutic',
                    'Commentary',
                    'Guide',
                    'healthcare',
                    'Non-Pharmaceutical']

    # TODO::implement some sort of smart database
    titles = Article_Sweep.Article_Sweep(keywords, bad_keywords, auto_params, manual_params).words
    words = Counter(titles.split()).most_common()
    # problems = []
    # for word in words:
    #     if word[1] > 2:
    #         problems.append(word)
    # print(problems)
    print('-------------------------------------------------------------------------------------------------------------------------\n')
    problems = [word for word in words if '�' not in word[0] if word[1] > 2]
    print(problems)

if __name__ == "__main__":
    main()